import React from 'react';
import Head from 'next/head';
import { NextPage } from 'next';

const Contact: NextPage = () => {
  return (
    <div>
      <Head>
        <title>EoinDev Blog | Contact</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
    </div>
  );
};

export default Contact;
