import React from 'react';
import Head from 'next/head';
import { NextPage } from 'next';
import { Layout } from '../components';

const Search: NextPage = () => {
  return (
    <div>
      <Head>
        <title>EoinDev Blog | Search</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout />
    </div>
  );
};

export default Search;
